version = 1
SPDX-PackageName = "KDChart"
SPDX-PackageSupplier = "<info@kdab.com>"
SPDX-PackageDownloadLocation = "https://www.github.com/KDAB/KDChart"

#misc source code
[[annotations]]
path = ["**.qrc", "**.ui", "**.xml", "**.kdx", "**.kxs", "**.conf", "**.csv", "**.cht", "**.map", "**.bat", "CMakePresets.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Klar채lvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "MIT"

#artwork
[[annotations]]
path = ["images/**.png", "docs/api/**.png", "examples/**/**.png", "images/**.svg", "src/KDChart/resources/**.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Klar채lvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "MIT"

#misc documentation
[[annotations]]
path = ["**md", "**.txt", "CHANGES", "src/TODO", "**.html", "docs/manual/**.pdf"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Klar채lvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "MIT"

#misc config files
[[annotations]]
path = [".pre-commit-config.yaml", ".codespellrc", ".krazy", ".cmake-format.py", ".clang-format", ".clazy", ".gitignore", ".mdlrc", ".mdlrc.rb", ".pep8", ".pylintrc", "docs/api/Doxyfile.cmake", "distro/**", "REUSE.toml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Klar채lvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "BSD-3-Clause"

#3rdparty
[[annotations]]
path = "cmake/ECM/modules/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "The KDE Project"
SPDX-License-Identifier = "BSD-3-Clause"

# doxygen awesome
[[annotations]]
path = "docs/api/doxygen-awesome.css"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 - 2023 jothepro"
SPDX-License-Identifier = "MIT"
